### ISSUE TITLE
In Process.spawn_process use self.args instead of sys.argv

### ISSUE THREAD

**Issue by robvdl** [ybrs/single-beat#23]
Because the args are passed to the Process constructor, it should be using self.args in the spawn_process method instead of sys.argv or I cannot send custom args unless I also override sys.argv.

I have my own Python script and constructing Process and calling run() myself, I found it out that way that the method spawn_process is not using self.args

Do you want me to send a patch?

**Comment by robvdl** [comment]
See #25

**Comment by ybrs** [comment]
Yes that should be using `self.args` not `sys.argv` because we are already passing sys.args to constructor on `run_process` 

I'll do a few checks this weekend and then merge your commit, thank you. 

I didn't understand the exact use case btw, you are extending `singlebeat.beat.Process` class ? Can you give more details if possible. Never thought there would be a need for that (that's why I'm curious and also probably why missed that error.)

**Comment by robvdl** [comment]
The use case is very specific to a project at work and probably not one you need to worry about or support at all. We were already using .ini files to store the redis connection URL which contains a password. However single-beat uses environment variables for this.

I didn't want to put the environment variable containing a password in our supervisor config file as well as then we would have to start encrypting that file too just like our .ini files, but also then the connection string is in two places. This supervisor config file ends up in our Debian package so it's not currently encrypted.

My use case is very specific and a bit non-standard. I have a python script that reads our ini file, sets up the environment variables, and then I was either going to call os.execp or just create a child process to call single-beat.

Only problem is I ran into a lot of issues so in the end I actually end up importing singlebeat and constructing Process and passing sys.argv[2:] in my case as args.

The problem is that one method was not using the args passed in but sys.argv which is our script.

By subclassing Process and "fixing" that method temporarily in my script I have been able to work around this for now. But having this PR means we don't need to subclass anymore.

**Comment by robvdl** [comment]
Anyway, long story why I am doing what I am is irrelevant here :)

But I believe that #25 can be merged safely, because in beat.py in the run_process entrypoint, it aready passes sys.argv[1:] to the constructor:

```python
process = Process(sys.argv[1:])
```

So really it doesn't change anything, but makes my life a bit easier as I don't have to copy the entire method over when I'm subclassing.

**Comment by ybrs** [comment]
Sorry it's been a bit busy for the last month for me. I merged the pull request related to this. Will update the package soon. 

Thank you.

**Comment by robvdl** [comment]
Thank you, much appreciated.
