### ISSUE TITLE
SINGLE_BEAT_WAIT_MODE=supervised is buggy when restarting "too fast"

### ISSUE THREAD

**Issue by robvdl** [ybrs/single-beat#29]
I was using supervisor, and with the SINGLE_BEAT_WAIT_MODE=supervisord environment variable if I restart my supervisor process "too fast" then the child would be terminated and not come back. This is with just one instance.

    sudo supervisorctl restart beat   # but the child dissapears now

But this would work fine

    sudo supervisorctrl stop beat
    # wait a second...
    sudo supervisorctl start beat

By using SINGLE_BEAT_WAIT_MODE=heartbeat, the issue went away, so it seems there is something not quite right with SINGLE_BEAT_WAIT_MODE=supervisord.

**Comment by ybrs** [comment]
This is interesting, can you run it with `LOG_LEVEL=debug` environment variable ?

Single beat should check if the `identifier` key is in redis and if there is it should just exit - so in supervised mode, in a single node, it should be either child beat process and single beat process, or none. 

It might be something like, something going on child process - like it needs to wait for a couple of seconds before exiting/flushing etc. and parent dies too quick, but it will be super helpful if you can copy paste a debug log.

Thank you.

**Comment by robvdl** [comment]
I will investigate in a few days as I need to verify it's not something I am doing myself. My identifier is definitely setup correctly.

But an odd thing I did notice on the first time I built my dev environment I kept seeing KeyboardInterrupt in stderr log when the daemon had started the first time, but then I find it was actually running fine so I'm not sure what caused that. I spent about an hour researching random KeyboardInterrupt being thrown and it seemed related to event loops when they get terminated.

The thing is that the SIGTERM and SIGINT handlers only get registered in the Process constructor so I was wondering if it is terminated before that possibly. Anyway, this is a wild speculation, I'll do some research early next week.

**Comment by robvdl** [comment]
With log level set to DEBUG the parent process has a constant stream of log messages about fence tokens and because the parent process is logging all the time then, it will flush the log lines from the child process.

The debug logging is a bit too verbose to leave on permanently though, but without it there is almost no logging happening from the parent process without it unless something goes wrong generally.

**Comment by robvdl** [comment]
I haven't been able to reproduce this, if I do see it again I'll reopen it then.
