### ISSUE TITLE
License Info in setup.py

### ISSUE THREAD

**Issue by felix-smashdocs** [ybrs/single-beat#33]
Hi,

the single-beat is really cool and I discovered one small thing:
When listing all the used packages of the project with `pip-licenses`, the single-beat lib will show up with license "unknown".
Perhaps you want to add this info to the setup.py to make this complete.
More info: https://pypi.org/project/pip-licenses/

Greetings,

Felix

**Comment by s4ke** [comment]
@felix-smashdocs please check if it works for you right now. 0.5.1 should have the version set.

**Comment by felix-smashdocs** [comment]
Yes, works for me. Thanks for the update!
