### ISSUE TITLE
When SINGLE_BEAT_HEARTBEAT_INTERVAL=60 two celery-beat instances are active

### ISSUE THREAD

**Issue by vdboor** [ybrs/single-beat#6]
I'd set `SINGLE_BEAT_HEARTBEAT_INTERVAL` to 60 sec, but this causes single-beat not to be aware of the other instance; two celery-beat instances were active at my servers.

**Comment by ybrs** [comment]
thanks, what was your SINGLE_BEAT_LOCK_TIME variable ?

**Comment by vdboor** [comment]
I didn't notice that option, so didn't touch it.

**Comment by ze-phyr-us** [comment]
Looks like @ybrs fixed this here: https://github.com/ybrs/single-beat/commit/260a387d63edb23f6f15c59ad9b56ee1fac2ee17#diff-087331828f4adc70805bc8a49b0c5f48R19
